### ISSUE TITLE
Not working anymore with stack-ide-0.1.0.0

### ISSUE THREAD

**Issue by rvion** [lukexi/stack-ide-sublime#17]
ping @chrisdone, @lukexi 
related to: https://github.com/commercialhaskell/stack-ide/issues/81

I just pulled latest version of stack-ide-sublime, stack-ide, and stack

```
stack --version
Version 0.1.5.0, Git revision f89f03c099c5405ed51462384cc60af5a62ade0a X86_64
```

when I ran subl, I got :

```
[SublimeStackIDE][NORM]: Initializing window 10
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /Users/rvion/dev/fastannonce
[SublimeStackIDE][NORM]: Kicking off window 10
[SublimeStackIDE][WARN]: Stack-IDE error:  stty: stdin isn't a terminal

[SublimeStackIDE][WARN]: Stack-IDE error:  stty: stdin isn't a terminal

[SublimeStackIDE][WARN]: Stack-IDE error:  Process exited with ExitFailure 1: /bin/stty cbreak -imaxbel

[SublimeStackIDE][WARN]: Stack-IDE error:  Process exited with ExitFailure 1: /bin/stty cbreak -imaxbel

[SublimeStackIDE][WARN]: Stack-IDE error:  
[SublimeStackIDE][NORM]: Stack-IDE stderr process ended.
```

so I ran 

```
➜  stack-ide git:(master) stack ide start
ide-backend-0.10.0: unregistering (missing dependencies: ide-backend-common)
ide-backend-common-0.10.0: unregistering (local file changes)
stack-ide-0.1.0.0: unregistering (missing dependencies: ide-backend, ide-backend-common, stack-ide-api)
stack-ide-api-0.1.0.0: unregistering (missing dependencies: ide-backend-common)
HUnit-1.2.5.2: copying precompiled package
parallel-3.2.0.6: copying precompiled package
parsec-3.1.9: copying precompiled package
regex-base-0.93.2: copying precompiled package
regex-posix-0.95.2: copying precompiled package
regex-compat-0.95.1: copying precompiled package
monads-tf-0.1.0.2: download
extensible-exceptions-0.1.1.4: download
hostname-1.0: download
hostname-1.0: configure
regex-tdfa-rc-1.1.8.3: download
hostname-1.0: build
extensible-exceptions-0.1.1.4: configure
extensible-exceptions-0.1.1.4: build
monads-tf-0.1.0.2: configure
hostname-1.0: install
extensible-exceptions-0.1.1.4: install
monads-tf-0.1.0.2: build
regex-tdfa-rc-1.1.8.3: configure
unbounded-delays-0.1.0.9: download
regex-tdfa-rc-1.1.8.3: build
unbounded-delays-0.1.0.9: configure
xml-1.3.14: download
unbounded-delays-0.1.0.9: build
xml-1.3.14: configure
xml-1.3.14: build
monads-tf-0.1.0.2: install
unbounded-delays-0.1.0.9: install
xml-1.3.14: install
test-framework-0.8.1.1: download
test-framework-0.8.1.1: configure
test-framework-0.8.1.1: build
test-framework-0.8.1.1: install
test-framework-hunit-0.3.0.1: download
test-framework-hunit-0.3.0.1: configure
test-framework-hunit-0.3.0.1: build
test-framework-hunit-0.3.0.1: install
regex-tdfa-rc-1.1.8.3: install
tasty-0.10.1.2: download
tasty-0.10.1.2: configure
tasty-0.10.1.2: build
tasty-0.10.1.2: install
Completed all 15 actions.
Usage: stack-ide [--ghc-option OPT] [--include PATH] [--rts-option OPT]
                 [--dist-dir DIR] [--dir DIR] [--local-work-dir DIR]
                 [--ide-backend-tools-path PATH] [--extra-path PATH]
                 [--package-db DIR] [--keep-tmp-files] [-v|--verbose]
                 [--version]
  Start a new session
Process exited with ExitFailure 1: /Users/rvion/.local/bin/stack-ide --verbose --include=/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/TestSuite/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/test/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/test/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/stack-ide-api/:/Users/rvion/dev/stack-ide/stack-ide-api/src/:/Users/rvion/dev/stack-ide/stack-ide-api/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/stack-ide-api/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/stack-ide/:/Users/rvion/dev/stack-ide/stack-ide/src/:/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/stack-ide/stack-ide/:/Users/rvion/dev/stack-ide/stack-ide/src/main/:/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --local-work-dir=/Users/rvion/dev/stack-ide/ --ide-backend-tools-path=/Users/rvion/dev/stack-ide/.stack-work/install/x86_64-osx/nightly-2015-08-12/7.10.2/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-08-12/7.10.2/bin/:/Users/rvion/.local/bin/:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin --dist-dir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-Wall --ghc-option=-fno-warn-unused-do-bind --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/ide-backend/ide-backend-common/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=filepath-1.4.0.0 --ghc-option=-package=directory-1.2.2.0 --ghc-option=-package=containers-0.5.6.2 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=mtl-2.2.1 --ghc-option=-package=async-2.0.2 --ghc-option=-package=aeson-0.8.0.2 --ghc-option=-package=unix-2.7.1.0 --ghc-option=-package=temporary-1.2.0.3 --ghc-option=-package=bytestring-trie-0.2.4.1 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=fingertree-0.1.1.0 --ghc-option=-package=binary-0.7.5.0 --ghc-option=-package=data-accessor-0.2.2.6 --ghc-option=-package=crypto-api-0.13.2 --ghc-option=-package=pureMD5-2.1.2.1 --ghc-option=-package=tagged-0.8.1 --ghc-option=-package=transformers-0.4.2.0 --ghc-option=-package=attoparsec-0.12.1.6 --ghc-option=-package=template-haskell --ghc-option=-package=pretty-show-1.6.8.2 --ghc-option=-package=monad-logger-0.3.13.2 --dist-dir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-Wall --ghc-option=-rtsopts --ghc-option=-with-rtsopts=-c --ghc-option=-with-rtsopts=-I0 --ghc-option=-dynamic --ghc-option=-XMonoLocalBinds --ghc-option=-XBangPatterns --ghc-option=-XRecordWildCards --ghc-option=-XNamedFieldPuns --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/ide-backend/ide-backend-server/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=ghc --ghc-option=-package=containers-0.5.6.2 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=data-accessor-0.2.2.6 --ghc-option=-package=data-accessor-mtl-0.2.0.4 --ghc-option=-package=async-2.0.2 --ghc-option=-package=unix-2.7.1.0 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=directory-1.2.2.0 --ghc-option=-package=filepath-1.4.0.0 --ghc-option=-package=process-1.2.3.0 --ghc-option=-package=transformers-0.4.2.0 --ghc-option=-package=mtl-2.2.1 --ghc-option=-package=unordered-containers-0.2.5.1 --ghc-option=-package=filemanip-0.3.6.3 --ghc-option=-package=array-0.5.1.0 --ghc-option=-package=temporary-1.2.0.3 --ghc-option=-package=tar-0.4.2.1 --ghc-option=-package=zlib-0.5.4.2 --ghc-option=-package=file-embed-0.0.8.2 --ghc-option=-package=time-1.5.0.1 --ghc-option=-package=haddock-api-2.16.1 --ghc-option=-package=Cabal-1.22.4.0 --dist-dir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-Wall --ghc-option=-fno-warn-unused-do-bind --ghc-option=-XMonoLocalBinds --ghc-option=-XBangPatterns --ghc-option=-XRecordWildCards --ghc-option=-XNamedFieldPuns --ghc-option=-XRankNTypes --ghc-option=-XMultiParamTypeClasses --ghc-option=-XExistentialQuantification --ghc-option=-XFlexibleContexts --ghc-option=-XDeriveDataTypeable --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=filemanip-0.3.6.3 --ghc-option=-package=process-1.2.3.0 --ghc-option=-package=filepath-1.4.0.0 --ghc-option=-package=directory-1.2.2.0 --ghc-option=-package=containers-0.5.6.2 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=mtl-2.2.1 --ghc-option=-package=async-2.0.2 --ghc-option=-package=unix-2.7.1.0 --ghc-option=-package=temporary-1.2.0.3 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=binary-0.7.5.0 --ghc-option=-package=data-accessor-0.2.2.6 --ghc-option=-package=data-accessor-mtl-0.2.0.4 --ghc-option=-package=pureMD5-2.1.2.1 --ghc-option=-package=transformers-0.4.2.0 --ghc-option=-package=time-1.5.0.1 --ghc-option=-package=attoparsec-0.12.1.6 --ghc-option=-package=utf8-string-1 --ghc-option=-package=template-haskell --ghc-option=-package=Cabal-ide-backend-1.23.0.0 --ghc-option=-package=ghc-prim --ghc-option=-package=pretty-show-1.6.8.2 --ghc-option=-Wall --ghc-option=-fno-warn-unused-do-bind --ghc-option=-XMonoLocalBinds --ghc-option=-XBangPatterns --ghc-option=-XRecordWildCards --ghc-option=-XNamedFieldPuns --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=filemanip-0.3.6.3 --ghc-option=-package=process-1.2.3.0 --ghc-option=-package=filepath-1.4.0.0 --ghc-option=-package=directory-1.2.2.0 --ghc-option=-package=containers-0.5.6.2 --ghc-option=-package=random-1.1 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=mtl-2.2.1 --ghc-option=-package=async-2.0.2 --ghc-option=-package=aeson-0.8.0.2 --ghc-option=-package=executable-path-0.0.3 --ghc-option=-package=unix-2.7.1.0 --ghc-option=-package=temporary-1.2.0.3 --ghc-option=-package=bytestring-trie-0.2.4.1 --ghc-option=-package=unordered-containers-0.2.5.1 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=fingertree-0.1.1.0 --ghc-option=-package=binary-0.7.5.0 --ghc-option=-package=data-accessor-0.2.2.6 --ghc-option=-package=data-accessor-mtl-0.2.0.4 --ghc-option=-package=crypto-api-0.13.2 --ghc-option=-package=pureMD5-2.1.2.1 --ghc-option=-package=tagged-0.8.1 --ghc-option=-package=transformers-0.4.2.0 --ghc-option=-package=time-1.5.0.1 --ghc-option=-package=attoparsec-0.12.1.6 --ghc-option=-package=template-haskell --ghc-option=-package=Cabal-ide-backend-1.23.0.0 --ghc-option=-package=ghc-prim --ghc-option=-package=pretty-show-1.6.8.2 --ghc-option=-Wall --ghc-option=-with-rtsopts=-N --ghc-option=-XRecordWildCards --ghc-option=-XNamedFieldPuns --ghc-option=-XDeriveDataTypeable --ghc-option=-XOverloadedStrings --ghc-option=-XScopedTypeVariables --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/TestSuite/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/test/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=tasty-0.10.1.2 --ghc-option=-package=HUnit-1.2.5.2 --ghc-option=-package=tagged-0.8.1 --ghc-option=-package=utf8-string-1 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=regex-compat-0.95.1 --ghc-option=-package=filepath-1.4.0.0 --ghc-option=-package=filemanip-0.3.6.3 --ghc-option=-package=process-1.2.3.0 --ghc-option=-package=directory-1.2.2.0 --ghc-option=-package=stm-2.4.4 --ghc-option=-package=unix-2.7.1.0 --ghc-option=-package=random-1.1 --ghc-option=-package=Cabal-ide-backend-1.23.0.0 --ghc-option=-package=containers-0.5.6.2 --ghc-option=-package=deepseq-1.4.1.1 --ghc-option=-package=parallel-3.2.0.6 --ghc-option=-package=monads-tf-0.1.0.2 --ghc-option=-Wall --ghc-option=-fno-warn-unused-do-bind --ghc-option=-XMonoLocalBinds --ghc-option=-XBangPatterns --ghc-option=-XRecordWildCards --ghc-option=-XNamedFieldPuns --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/test/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/ide-backend/ide-backend/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=directory-1.2.2.0 --ghc-option=-package=filemanip-0.3.6.3 --ghc-option=-package=process-1.2.3.0 --ghc-option=-package=filepath-1.4.0.0 --ghc-option=-package=containers-0.5.6.2 --ghc-option=-package=random-1.1 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=async-2.0.2 --ghc-option=-package=aeson-0.8.0.2 --ghc-option=-package=temporary-1.2.0.3 --ghc-option=-package=test-framework-0.8.1.1 --ghc-option=-package=test-framework-hunit-0.3.0.1 --ghc-option=-package=HUnit-1.2.5.2 --ghc-option=-package=executable-path-0.0.3 --ghc-option=-package=unix-2.7.1.0 --ghc-option=-package=binary-0.7.5.0 --ghc-option=-package=template-haskell --dist-dir=/Users/rvion/dev/stack-ide/stack-ide-api/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-Wall --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide-api/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide-api/src/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide-api/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide-api/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/stack-ide-api/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/stack-ide-api/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=aeson-0.8.0.2 --ghc-option=-package=unordered-containers-0.2.5.1 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=text-1.2.1.3 --dist-dir=/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-Wall --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/src/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=async-2.0.2 --ghc-option=-package=aeson-0.8.0.2 --ghc-option=-package=ansi-wl-pprint-0.6.7.2 --ghc-option=-package=attoparsec-0.12.1.6 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=directory-1.2.2.0 --ghc-option=-package=filepath-1.4.0.0 --ghc-option=-package=optparse-applicative-0.11.0.2 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=haskell-src-exts-1.16.0.1 --ghc-option=-Wall --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/src/main/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/stack-ide/stack-ide/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=aeson-0.8.0.2 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=Cabal-1.22.4.0 --ghc-option=-package=fast-logger-2.4.0 --ghc-option=-package=gitrev-1.1.0 --ghc-option=-package=monad-logger-0.3.13.2 --ghc-option=-package=text-1.2.1.3 --package-db=/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-08-12/7.10.2/pkgdb/:/Users/rvion/dev/stack-ide/.stack-work/install/x86_64-osx/nightly-2015-08-12/7.10.2/pkgdb/
```

second try to start ide:

```
stack ide start
Usage: stack-ide [--ghc-option OPT] [--include PATH] [--rts-option OPT]
                 [--dist-dir DIR] [--dir DIR] [--local-work-dir DIR]
                 [--ide-backend-tools-path PATH] [--extra-path PATH]
                 [--package-db DIR] [--keep-tmp-files] [-v|--verbose]
                 [--version]
  Start a new session
Process exited with ExitFailure 1: /Users/rvion/.local/bin/stack-ide --verbose --include=/Users/rvion/dev/fastannonce/:/Users/rvion/dev/fastannonce/src/:/Users/rvion/dev/fastannonce/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/fastannonce/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/:/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --local-work-dir=/Users/rvion/dev/fastannonce/ --ide-backend-tools-path=/Users/rvion/dev/fastannonce/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/lts-3.4/7.10.2/bin/:/Users/rvion/.local/bin/:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin --dist-dir=/Users/rvion/dev/fastannonce/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-i/Users/rvion/dev/fastannonce/ --ghc-option=-i/Users/rvion/dev/fastannonce/src/ --ghc-option=-i/Users/rvion/dev/fastannonce/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/fastannonce/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/fastannonce/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/fastannonce/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=Spock-0.8.1.0 --ghc-option=-package=websockets-0.9.5.0 --ghc-option=-package=wai-websockets-3.0.0.6 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=transformers-0.4.2.0 --ghc-option=-package=wai-middleware-static-0.7.0.1 --ghc-option=-package=wai-extra-3.0.10 --ghc-option=-package=iproute-1.5.0 --dist-dir=/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-Wall --ghc-option=-i/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/ --ghc-option=-i/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/rvion/dev/fastannonce/.stack-work/downloaded/ac26149816c1abebfe3489bf78963a7dfe873ba26a53361380411e61178b1747.git/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package=base --ghc-option=-package=bytestring-mmap-0.2.2 --ghc-option=-package=bytestring-0.10.6.0 --ghc-option=-package=binary-0.7.5.0 --ghc-option=-package=text-1.2.1.3 --ghc-option=-package=containers-0.5.6.2 --ghc-option=-package=iproute-1.5.0 --ghc-option=-package=reinterpret-cast-0.1.0 --package-db=/Users/rvion/.stack/snapshots/x86_64-osx/lts-3.4/7.10.2/pkgdb/:/Users/rvion/dev/fastannonce/.stack-work/install/x86_64-osx/lts-3.4/7.10.2/pkgdb/
```

I'm really interested in sorting that out.
any pointer ?

**Comment by rvion** [comment]
more commands in case it helps

```
$ stack ide packages
fastannonce
geoip2
```

```
$ stack ide load-targets fastannonce
src/Annonce.hs
src/Geo.hs
src/Main.hs
src/WS.hs
.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/Paths_fastannonce.hs
```

**Comment by chrisdone** [comment]
I fixed that error on stack master.

The problem was that on OS X if your program is run in a tty then `fgets` prints a BEL character to stdout whenever it receives a line of text larger than its default max. Emacs launches processes in a pseudo-TTY, so this was causing communication to fail on OS X. The `stty` call disables this behaviour. Obviously, this SublimeText plugin is launching the process as a pipe not in a pseudo-TTY so the `stty` call fails. On master it now ignores this error.

**Comment by rvion** [comment]
It doesn't seem to work for me: 
stack-ide still consumes request without waiting for new lines, and crash at various input

Version 0.1.5.0, Git revision 58f6ebc78ba391ef987cf6e502e597dbcd6672db X86_64

**Comment by chrisdone** [comment]
The newlines shouldn't matter, stack-ide consumes using attoparsec's incremental parsing.

**Comment by rvion** [comment]
thanks for the pointer, so the only thing is that the crash bug remain with sublime-stack-ide (and when pressing `up` on the terminal prompt for example)

**Comment by lukexi** [comment]
Hi Remi, things should be working now once the above mentioned pull request is integrated — grab the latest stack-ide-sublime and let me know : )

(sorry it took so long, lots of traveling this month and have been stuck on Windows where we only just got stack-ide working last week : ) )

**Comment by rvion** [comment]
@lukexi I'll have a look real soon :)
Big thanks for all the good work :+1:

**Comment by rvion** [comment]
so far, it's not working yet: https://github.com/commercialhaskell/stack-ide/issues/94
I'll try again now: I'll wipe out all my haskell installation, then retry from scratch to install everything

**Comment by rvion** [comment]
Yay, all working !  (with your branch https://github.com/commercialhaskell/stack/pull/1204 merged)

**Comment by borsboom** [comment]
https://github.com/commercialhaskell/stack/pull/1204 is merged.

**Comment by lukexi** [comment]
Yahoo! Thanks all
